add porymophic comment
universato/rails_fjord_books pull request #8
Opened 2020-09-27 02:44 UTC by universato

2020-09-28 07:56 UTC, komagata requested changes

2020-09-28 07:56 UTC, komagata commented on app/assets/stylesheets/reports.scss
> +// Place all the styles related to the reports controller here.
scaffoldでできるこれ系のファイルは不要であれば削除しちゃってください〜

2020-09-28 07:56 UTC, komagata commented on app/controllers/comments_controller.rb
> +      resource, id = request.path.split("/")[1, 2]
👍

2020-09-28 10:26 UTC, universato commented on app/assets/stylesheets/reports.scss
> +// Place all the styles related to the reports controller here.
削除しました

2020-09-29 12:36 UTC, komagata requested changes

2020-09-29 12:36 UTC, komagata commented on test/fixtures/users.yml
> +  uid: 2
最終行に改行がないようです〜

2020-09-29 17:04 UTC, universato commented on test/fixtures/users.yml
> +  uid: 2
エディタは自動で最終行に改行が入る設定なので、GitHub上でコンフリクト解消したときに入ってしまったようです。解消しました。

2020-09-30 06:26 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-09-30 11:27 UTC, merged